baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Regions'
pageRef = '#'
weight = 20

[[menus.main]]
name = 'Himalayas'
pageRef = '/regions/himalayas'
weight = 100
parent = "Regions"

[[menus.main]]
name = 'North'
pageRef = '/regions/north'
weight = 110
parent = "Regions"

[[menus.main]]
name = 'West and Central'
pageRef = '/regions/west-and-central'
weight = 120
parent = "Regions"

[[menus.main]]
name = 'South'
pageRef = '/regions/south'
weight = 130
parent = "Regions"

[[menus.main]]
name = 'East and North-East'
pageRef = '/regions/east-and-northeast'
weight = 140
parent = "Regions"

[[menus.main]]
name = 'Islands'
pageRef = '/regions/islands'
weight = 150
parent = "Regions"

[[menus.main]]
name = 'Buy the Book'
pageRef = '/shop'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/shop'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
